version: '3.6'
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.data/db_data:/var/lib/postgresql/data:delegated

  gql:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_ADMIN_SECRET: password
      HASURA_GRAPHQL_MIGRATIONS_DIR: /project/migrations
      HASURA_GRAPHQL_METADATA_DIR: /project/metadata
    volumes:
      - ./hasura:/project
    ports:
      - "5000:8080"
